### ISSUE TITLE
Multithreaded Noise taken down/removed?

### ISSUE THREAD

**Issue by JonaldJohnston** [Red-Studio-Ragnarok/Opticraft#1]
Was Multithreaded Noise removed? The link on the Opticraft page leads gives a 500 error on Curseforge and searching for it on Curseforge itself turns up nothing. Anyone know what happened?

**Comment by Desoroxxx** [comment]
Weird...

It seems to be down on the beta website hope they fix it, for now you can use legacy Curse Forge https://legacy.curseforge.com/minecraft/mc-mods/multithreaded-noise

**Comment by JonaldJohnston** [comment]
Huh, that's strange. Thanks for the response.

**Comment by Desoroxxx** [comment]
Need to precise it won't be needed much anyway after one of my projects releases
