### ISSUE TITLE
Better FPS?

### ISSUE THREAD

**Issue by XvaleX10** [Red-Studio-Ragnarok/Opticraft#13]
## Why the mod should be added to Opticraft
Changes sin() and cos() algorithm. There are 7 algorithms. Each one of them may or may not help you, it really depends on the hardware of your computer.

## Link to the **real** mod page
https://www.curseforge.com/minecraft/mc-mods/betterfps
Ex: https://www.curseforge.com/minecraft/mc-mods/fbp

## Optional Informations

- [x] Did you verify if the mod actually does what it says
- [ ] Are affiliated in any way with the mod (Being the dev, knowing the devs, etc.)

> Additional information is not a criteria in any way it just helps me in my research

**Comment by Desoroxxx** [comment]
No improvements were able to be found, and most functions are replaced by other mods.
