### ISSUE TITLE
FermiumASM instead CensoredASM

### ISSUE THREAD

**Issue by XvaleX10** [Red-Studio-Ragnarok/Opticraft#14]
## Why the mod should be added to Opticraft
As with the original and the forks, FermiumASM makes multiple improvements, optimizations, and bug fixes to Minecraft, including but not limited to:
- Optimizing RAM usage, especially in larger packs.
- Fixing multiple crashes, in Minecraft, Forge, and some other mods.
- Multiple performance improvements.
- Crash handling to allow you directly upload crash reports to mclo.gs.
While the NormalASM forks only rebranded and stayed updated with CensoredASM, FermiumASM on the other hand does more significant changes to its function:
- Refactored and modified to use and depend on FermiumBooter, an MIT alternative to mixin loading, replacing its dependency on MixinBooter.
- Modified to remove internal dependency on MixinExtras.
- Removes internal Spark profiling as it is both incompatible with, and superseded by, the updated fork Spark Unforged, allowing for better profiling.
- Removes the chance to pick a random author to blame in a crash report.
- Rebranded user-facing and logging branding, including icon and url, to FermiumASM, and updated authors to recognize fork authors.

## Link to the **real** mod page
https://www.curseforge.com/minecraft/mc-mods/fermiumasm
Ex: https://www.curseforge.com/minecraft/mc-mods/fbp

## Optional Informations

- [x] Did you verify if the mod actually does what it says
- [ ] Are affiliated in any way with the mod (Being the dev, knowing the devs, etc.)

> Additional information is not a criteria in any way it just helps me in my research

**Comment by KorewaLidesu** [comment]
***Warning:*** *This is my opinion about the mod, please take it as reference.*

Currently stage of FermiumASM hasn't improved much outside of CensoredASM from what I can tell here:
- Rebranding.
- Replace depencencies.
- Remove VFix "random author blame" feature.
- Remove hard depend on old Spark version.

Yes, I do know that it has new commits comparing to the mod's parent.
But, unless there is a benchmark that can show improvement in performance, I don't think it is worth to switch the mod.

**Comment by XvaleX10** [comment]
> _**Warning:**_ _This is my opinion about the mod, please take it as reference._
> 
> Currently stage of FermiumASM hasn't improved much outside of CensoredASM from what I can tell here:
> 
> * Rebranding.
> * Replace depencencies.
> * Remove VFix "random author blame" feature.
> * Remove hard depend on old Spark version.
> 
> Yes, I do know that it has new commits comparing to the mod's parent. But, unless there is a benchmark that can show improvement in performance, I don't think it is worth to switch the mod.

I did a test in my 115 mod pack and I got a better result with FermiumASM than CensoredASM with 150mb less ram usage and almost 20 fps more

**Comment by Desoroxxx** [comment]
After carefully looking at the difference between the source code of both mods, the only real difference lowers performance.

https://github.com/skmedix/NormalASM/compare/dev/sync-5.14...fonnymunkey:FermiumASM:dev/sync-5.14#diff-fb3677654896c395344102ed8ef1fc1f55dc791c958e7fffae3adb2ab346638eL30-R32

In addition Fermium ASM is outdate and lacks important changes.

**Comment by fonnymunkey** [comment]
Can you elaborate on what the performance issues are, I have not had this reported before and I see no changes that would cause such an issue?

Additionally it is now fully up to date along with newer changes, Curseforge approval took nearly 2 weeks so I preferred to bundle multiple changes at once over staying fully up to date instantly.

**Comment by Desoroxxx** [comment]
> Can you elaborate on what the performance issues are, I have not had this reported before and I see no changes that would cause such an issue?
> 
> Additionally it is now fully up to date along with newer changes, Curseforge approval took nearly 2 weeks so I preferred to bundle multiple changes at once over staying fully up to date instantly.


`@Inject` for example has lower performance than `@ModifyReturnValue` additionally it completly destroys compatibility with other mods

**Comment by fonnymunkey** [comment]
From my testing the performance difference is non-significant during actual gameplay, however for the sake of compatibility concerns I've restored the MixinExtras usage in the latest 5.23 release which is now uploaded, along with re-synced upstream (Which is now ahead of NormalASM.)
