### ISSUE TITLE
Broken changelog link

### ISSUE THREAD

**Issue by roidrole** [Red-Studio-Ragnarok/Opticraft#15]
On the website, there is la link names "V1.13" which links to https://github.com/Red-Studio-Ragnarok/Opticraft/blob/main/changelog.md
Turns out the link to the changelog is https://github.com/Red-Studio-Ragnarok/Opticraft/blob/main/Changelog.md

This results in a broken link

**Comment by Desoroxxx** [comment]
Thanks, it should be fixed now
