### ISSUE TITLE
Dry Alternate Current

### ISSUE THREAD

**Issue by Floi1** [Red-Studio-Ragnarok/Opticraft#2]
## First Thing First

Let's define precisely what is an optimization mod:

It improves the game by either improving performance (making it faster) or making it more ressource efficient (using less of your CPU/GPU/etc.).

But it needs to do so without removing a feature or making said feature worse or in the case of making the game more ressource efficient it needs to do so without reducing performance.

## Why the mod should be added to Opticraft
It should be added because people who run servers could find this mod useful 

***A clear and concise description of what the mod optimizes or fix.***

Alternate Current is an efficient and non-locational redstone dust implementation. Its main focus lies in reducing the lag caused by redstone dust, by optimizing the power calculations and reducing the number of shape and block updates emitted. As a side effect of these changes the block update order of redstone dust networks is predictable and intuitive rather than locational and chaotic.
Ex: SuperOptimizationMod optimizes [...] and fixes [...].

## Link to the **real** mod page

***Just the link to the real page of the mod no 9minecraft or other malware site***

https://legacy.curseforge.com/minecraft/mc-mods/dry-alternate-current
Ex: https://www.curseforge.com/minecraft/mc-mods/fbp

## Optional Informations

- [ ] Did you verify if the mod actually does what it says
- [ ] Are affiliated in any way with the mod (Being the dev, knowing the devs, etc.)

> Additional information is not a criteria in any way it just helps me in my research

**Comment by Desoroxxx** [comment]
https://github.com/hampop/alternate-current-1.12.2-/tree/dry-alternate-current-1.12.2

It seems that this mod is literally empty and does nothing
