### ISSUE TITLE
Resource packs not loading with mods

### ISSUE THREAD

**Issue by Kevkkkkk** [Red-Studio-Ragnarok/Opticraft#20]
I am making a modpack dependent on the Conquest Reforged resource pack however resource packs do not load at all, I get booted to the main menu and none of the packs are loaded after spending time loading. I am running a 21 mod profile that only has the optimization mods plus extras like JEI and Hwyla. 

Full list here:
Alfheim-1.4.jar
censoredasm5.20.jar
!configanytime-3.0.jar
Controlling-3.0.12.4.jar
dynviewdist-1.12-1.3.jar
EntityCulling-1.12.2-6.4.3.jar
Fixeroo-2.3.2.jar
Hwyla-1.8.26-B41_1.12.2.jar
Jade-0.1.0.jar
jei_1.12.2-4.16.1.301.jar
!mixinbooter-10.2.jar
_MixinBootstrap-1.1.0.jar
MouseTweaks-2.10-mc1.12.2.jar
NetherPortalFix_1.12.1-5.3.17.jar
Nothirium-1.12.2-0.3.4-beta.jar
particleculling-1.12.2-v1.4.3.jar
!Red-Core-MC-1.8-1.12-0.6-Dev-8.jar
RenderLib-1.12.2-1.3.5.jar
Sledgehammer-1.12.2-2.0.26.jar
UniversalTweaks-1.12.2-1.13.0.jar
vintagefix-0.5.1.jar

Any insights into what mod is causing this issue would be appreciated.
Thanks!

**Comment by xskutsu** [comment]
Easiest way to determine what mod is the problem is to disable half of them, check if the issue still exists, if it does then disable half of the remaining enabled mods, if it doesnt then enable half of the disabled mods, keep repeating this until you narrow it down to one mod.

**Comment by Kevkkkkk** [comment]
Issue was vintage fix
