### ISSUE TITLE
Tidy chunk an optimization mod?

### ISSUE THREAD

**Issue by dazadazu** [Red-Studio-Ragnarok/Opticraft#3]
## First Thing First

Let's define precisely what is an optimization mod:

It improves the game by either improving performance (making it faster) or making it more ressource efficient (using less of your CPU/GPU/etc.).

But it needs to do so without removing a feature or making said feature worse or in the case of making the game more ressource efficient it needs to do so without reducing performance.

## Why the mod should be added to Opticraft

***A clear and concise description of what the mod optimizes or fix.***

Ex: SuperOptimizationMod optimizes [...] and fixes [...].

## Link to the **real** mod page

***Just the link to the real page of the mod no 9minecraft or other malware site***

Ex: https://www.curseforge.com/minecraft/mc-mods/fbp

## Optional Informations

- [ ] Did you verify if the mod actually does what it says
- [ ] Are affiliated in any way with the mod (Being the dev, knowing the devs, etc.)

> Additional information is not a criteria in any way it just helps me in my research

**Comment by dazadazu** [comment]
https://www.curseforge.com/minecraft/mc-mods/tidychunk

**Comment by ACGaming** [comment]
Already part of [Universal Tweaks](https://www.curseforge.com/minecraft/mc-mods/universal-tweaks)! 😉

**Comment by Desoroxxx** [comment]
> Already part of [Universal Tweaks](https://www.curseforge.com/minecraft/mc-mods/universal-tweaks)! 😉

Closing this then (how did I not get a notification?)
