### ISSUE TITLE
Add VintageFix

### ISSUE THREAD

**Issue by JuiceyBeans** [Red-Studio-Ragnarok/Opticraft#5]
## Why the mod should be added to Opticraft
[Significant memory usage reduction](https://i.imgur.com/xcJmI9y.png), reduces load times and resource pack reload times pretty decently. Replaces FoamFix and VanillaFix entirely. Effectively is a modified backport of FerriteCore to 1.12.2

## Link to the **real** mod page
https://www.curseforge.com/minecraft/mc-mods/vintagefix

## Optional Informations
- Did you verify if the mod actually does what it says: Yes, modpacks tested:
1. Enigmatica 2 Expert Unofficial: 3.5GB RAM during late midgame
2. Multiblock Madness: 3.5GB RAM early game
3. Meatballcraft Dimensional Ascension: 6GB RAM
4. Nomifactory: 1.5GB RAM :skull: (IV tier aka late midgame/early endgame)
5. Divine Journey 2: 2GB during early game, 3-4GB during midgame

Note: ~60FPS with Vsync and fancy graphics (no mipmap) on all modpacks except Meatballcraft, which averaged ~30FPS on fast graphics because of low end CPU specs and it being a pretty beefy pack in general.

- Are affiliated in any way with the mod (Being the dev, knowing the devs, etc):
 Yep, we are both active in a common Discord, I also bugtested alpha versions of the mod and submitted multiple bug reports and incompatibilities with other mods

**Comment by Desoroxxx** [comment]
Added in version 1.10
