### ISSUE TITLE
Move Fixeroo to Server and Client section

### ISSUE THREAD

**Issue by Vetpetmon** [Red-Studio-Ragnarok/Opticraft#7]
![image](https://github.com/Red-Studio-Ragnarok/Opticraft/assets/10699805/65a78618-d4bc-4961-b0f7-7b83ce088317)

![image](https://github.com/Red-Studio-Ragnarok/Opticraft/assets/10699805/22bb07b4-a493-493f-8fcc-e5be0310bfce)

Both the client and the server need the mod in order to function, putting it under "Server Only" is misleading.

**Comment by Vetpetmon** [comment]
Fixeroo shows up as XP Orb Clump with it's internal name. The JAR I am using is found here:
https://www.curseforge.com/minecraft/mc-mods/xp-orb-clump/files/4412006

**Comment by Desoroxxx** [comment]
Yeah will look into it with the author

**Comment by Desoroxxx** [comment]
Fixed for 1.11
