### ISSUE TITLE
Alfheim should be added to opticraft

### ISSUE THREAD

**Issue by darklysteamgear** [Red-Studio-Ragnarok/Opticraft#9]
## Why the mod should be added to Opticraft
The mod is a fork of Hesperus, which aims to add even more fixes to the lighting engine then Hesperus added. It is currently being maintained as well. I have verified the mod works better then Hesperus. I've seen reduction in RAM usage when switching from Hesperus to Alfheim as my lighting optimization mod in my large modpack.

## Link to the **real** mod page

Ex: https://www.curseforge.com/minecraft/mc-mods/alfheim-lighting-engine

## Optional Informations

 It is made by the same guy that created Valkyrie.

**Comment by Desoroxxx** [comment]
> It is made by the same guy that created Valkyrie.

Is that ***girl*** named Desoroxxx perhaps?

I will update Opticraft tomorrow

**Comment by Desoroxxx** [comment]
Done in version 1.12
